all:
  children:
    masters:
      hosts:
        k8s-master:
          ansible_host: 10.11.66.10

    workers:
      hosts:
        k8s-worker1:
          ansible_host: 10.11.66.11
        k8s-worker2:
          ansible_host: 10.11.66.12