all:
  children:
    master:
      hosts:
        master:
          ansible_host: 10.11.66.113
    workers:
      hosts:
        worker1:
          ansible_host: 10.11.66.11
        worker2:
          ansible_host: 10.11.66.12
