all:
  children:
    masters:
      hosts:
        master:
          ansible_host: 10.11.66.10

    workers:
      hosts:
        worker1:
          ansible_host: 10.11.66.11
        worker2:
          ansible_host: 10.11.66.12