- hosts: masters
  become: yes
  tasks:

    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: init_output
      ignore_errors: yes  # لتجنب توقف Playbook لو فشل init

    - name: Extract kubeadm join command
      set_fact:
        kube_join_cmd: >-
          {{ init_output.stdout_lines
             | select('search', 'kubeadm join')
             | list
             | join(' ')
          }}