- hosts: all
  become: yes
  tasks:

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd
        state: present

    - name: Create containerd config
      command: containerd config default
      register: containerd_config

    - name: Save containerd config
      copy:
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml
      when: containerd_config is defined

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
