- name: Initialize cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Setup kubeconfig
  shell: |
    mkdir -p /root/.kube
    cp /etc/kubernetes/admin.conf /root/.kube/config
    chmod 600 /root/.kube/config
