- hosts: master
  become: yes

  tasks:
  
- name: Check if Calico installed
  command: kubectl get daemonset calico-node -n kube-system
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: calico_check
  ignore_errors: yes

- name: Install Calico
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: calico_check.rc != 0
