- hosts: master
  become: yes
  tasks:

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_cmd

    - name: Join workers to cluster
      become: yes
      delegate_to: "{{ item }}"
      command: "{{ join_cmd.stdout }}"
      loop: "{{ groups['workers'] }}"
