- hosts: all
  become: yes
  tasks:

    - name: Disable swap
      command: swapoff -a

    - name: Remove swap from fstab
      lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent

    - name: Load kernel modules
      command: modprobe {{ item }}
      loop:
        - overlay
        - br_netfilter

    - name: Enable required sysctl params
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { key: net.bridge.bridge-nf-call-iptables, value: 1 }
        - { key: net.bridge.bridge-nf-call-ip6tables, value: 1 }
        - { key: net.ipv4.ip_forward, value: 1 }
